### ISSUE TITLE
Is it possible to accept the rules of the competition via the API?

### ISSUE THREAD

**Issue by vinzeebreak** [Kaggle/kaggle-api#104]
If not, has it been considered?

I ask this question because I need to download several datasets from several competitions that correspond to some criteria of my own. But the number of competitions that interest me is sufficiently high so that it's a pain to accept the rules by going on my browser and clicking on "Accept the rules".

**Comment by mrisdal** [comment]
No, it's not possible to accept competition rules via the API. It's not likely that we will prioritize this as a feature, either. Because the rules are a contract between the participant and competition host,  competitions participants should read and understand the rules prior to accepting them. Reading them on the website is the preferred way to do this. Hope that makes sense and I do apologize that this does interrupt your flow.
