### ISSUE TITLE
how' can i download the dataset

### ISSUE THREAD

**Issue by uplow** [Kaggle/kaggle-api#135]
I am a newbie, how can I download the whole dataset?It is only possible to download sample data using kaggle competitions download-c two-sigma-financial news

**Comment by rysteboe** [comment]
The API only permits downloading the same data that is available on the data tab of the competition (https://www.kaggle.com/c/two-sigma-financial-news/data).  For some competitions like Two Sigma, we do not make the full dataset downloadable, since the intent is that the data is accessed and analyzed in the Kaggle Kernels environment.
