### ISSUE TITLE
submit problem for qqp dataset 

### ISSUE THREAD

**Issue by pangjh3** [Kaggle/kaggle-api#136]
I am trying to submit my test results for quora question pairs datasets, but suffer from the following problems. Can anyone give me a hint?
![image](https://user-images.githubusercontent.com/16623530/50149616-a5e57700-02f6-11e9-8358-c3435731b6ec.png)

**Comment by SkyFlyboy** [comment]
I have update the kaggle api and use python3 .

**Comment by rysteboe** [comment]
Did this happen at (roughly) the same time you posted this issue?

**Comment by SkyFlyboy** [comment]
> Did this happen at (roughly) the same time you posted this issue?

yes, I try in today morning, the problem still happened.

**Comment by rysteboe** [comment]
Are you by chance in China?

**Comment by SkyFlyboy** [comment]
> Are you by chance in China?

yes, Is there any problems? I also set up a vpn but it still didn't work.

**Comment by rysteboe** [comment]
Sorry, I've been on holiday for a couple of weeks.  Unfortunately it's likely that the problem is related to either the VPN or your location, and I don't have a great way to debug either.  I'll add this to my investigation list, but I can't make any promises right now on a good fix/workaround.  With any luck, someone else who has run into this will find a solution.

**Comment by Philmod** [comment]
I can't reproduce this bug, feel free to reopen if you are still experiencing it.
