### ISSUE TITLE
feature request: kaggle datasets delete

### ISSUE THREAD

**Issue by virilo** [Kaggle/kaggle-api#175]
It could make easier to delete private datasets during the competition (checkpoints, etc).
Also to perform a cleansing after the competition end.

Regarding public datasets, perhaps it could be safer to keep this functionality via browser... ¯\_(ツ)_/¯

**Comment by bothmena** [comment]
Hi @virilo, 

I don't know exactly what you want to achieve here, but, have you tried removing the dataset from kernel-metadata.json file and pushing the kernel again?

**Comment by virilo** [comment]
Hi @bothmena,

I'm using lots of temporal datasets with the same purpose:

    train NN 9 hours --> output: checkpoint --> save output as temporal dataset --> resume training for 9 hours

So these datasets are only an intermediate storage between kernel executions.

Once the training has been resumed, the temporal datasets are no more longer needed.

We have a quota of 20GB space for datasets.  So I've to delete them manualy (via kaggle web)

It could be great to delete them using the kaggle api, instead of browsing.

> have you tried removing the dataset from kernel-metadata.json file and pushing the kernel again?
I think it doesn't solve the 20GB space limit for my kaggle user

Thanks in advance

**Comment by bothmena** [comment]
I think you're not making use of kernel output as a data source: 
in the kernel-metadata.json
*Note that you're using the output of the same kernel!*

> **NB**: you need to pay attention to the name of the kernel! If you name the kernel: "My Kernel" then the id of the kernel will be: "username/my-kernel"
```
{
  "id": "username/my-awesome-kernel",
  "title": "My Awesome Kernel",
  # ...
  "kernel_sources": ["username/my-awesome-kernel"]
}
```
Now, you can access the output of the previous commit from the current running commit.
**Here I assume that you are saving the network weights in a dataset to load them later and resume training**
To do this, all you have to do is, save the output with the same filename every time. 
**Before you start training**
```
# check if there is a file in the input directory, you need to do 
# this because in the first commit you won't have any input files 
# from the previous kernel because there is no previous kernel.

import os
if os.path.isfile(''../input/my_net_state.pt''):
    model.load_state_dict(torch.load(''../input/my_net_state.pt''))
    model.eval()
```
When you're done training, you save the network weights as output.
```
torch.save(model.state_dict(), 'my_net_state.pt')
```

**You only can do this if the total size of your output is less than 5Go, and the total number of files is less than 500, otherwise, the commit will fail.**

I hope my suggestion helps.

**Comment by virilo** [comment]
thanks @bothmena !

yes, it was what I needed indeed.

You have saved me a lot of time!
