### ISSUE TITLE
Error listing all my kernels from kaggle api cli (error 500)

### ISSUE THREAD

**Issue by virilo** [Kaggle/kaggle-api#178]
If I simply list with:

    kaggle kernels list
    kaggle kernels list --mine -p 1

Both are working.

But all the next are failing:

    kaggle kernels list --mine -p 2
    kaggle kernels list --mine --page-size 99 -p 1
    kaggle kernels list --mine --page-size 99

    500 - An internal server error occurred. Please ensure that your API client is up to date. If it is, please report a bug at github.com/Kaggle/kaggle-api

So, I can't list all my kernels

I'm using the last client version 1.5.3:

    pip show kaggle
    Name: kaggle
    Version: 1.5.3
    Summary: Kaggle API
    Home-page: https://github.com/Kaggle/kaggle-api
    Author: Kaggle
    Author-email: support@kaggle.com

Until April the 28th, I was able to execute kaggle kernels list --mine --page-size 10000000

**Comment by virilo** [comment]
Now, I'm also having the 500 error with "kaggle kernels push"

It seems to be something related to the server side, because I'm repeating the same 'push', in the same directory where I did a succeed 'push' some hours ago

I've the feeling I've been banned by an "intelligent" firewall, SIEM, or something like that due to my continuous tests.
Could it be?

**Comment by bothmena** [comment]
Hi @virilo,

I can't speak for the `kaggle k list` command, but I have been trying to push some kernels using the API and it fails almost every time!

I found out that the problem was with the name of the kernel if it's longer than 50 it will automatically return a 500 error. I have a pull request that suggests a solution for this problem, but I can't promise that every 500 error is caused by the kernel name in the metadata json file.

**Comment by virilo** [comment]
Thanks @bothmena 

> I found out that the problem was with the name of the kernel if it's longer than 50 it will automatically return a 500 error.

Thanks a lot for the info.  I'll validate this limit before pushing the kernel

Regarding the "kaggle kernels list ...", I just have tried "kaggle kernels list --mine --page-size 99" again, and I'm still having the 500 error.

**Comment by bothmena** [comment]
I have already fixed the problem of kernel length validation and waiting to merge my pull request. you can find the solution [here](https://github.com/bothmena/kaggle-api/commit/9906ad47e4dfd71efdc5005765390393c7b93861).

 Of course, you don't need to add the print lines I added, I removed them in the second commit.

I believe the 500 server error is due to poor handling of user input! the server should return a 40x error with a message that indicates what the user did wrong.

**Comment by dk-forestry** [comment]
> kaggle kernels list --mine --page-size 99
> 
> 500 - An internal server error occurred. Please ensure that your API client is up to date. If it is, please report a bug at github.com/Kaggle/kaggle-api

I just run into the same problem. Funnily enough, any `--page-size` less or equal than 50 works without problems, whereas anything greater than 50 returns the error. 

By the way, I probably have around 50 kernels on kaggle, so this number might be related to the number of kernels of a user.

**Comment by YuliaZhou** [comment]
I run into the same problem. I cannot get data after 51 pages. Does it have solutions?
![image](https://user-images.githubusercontent.com/15163136/100930799-30591e00-34af-11eb-98f5-8c4751247c79.png)

**Comment by gabriben** [comment]
same for me with
`kaggle kernels list -m`

`kaggle kernels list` does work though

**Comment by Rivosoa** [comment]
I have the same problem in version 1.5.12

`kaggle kernels list` works fine

But `kaggle kernels list` fails with error `500 - An internal server error occurred. Please ensure that your API client is up to date. If it is, please report a bug at github.com/Kaggle/kaggle-api`

**Comment by Philmod** [comment]
I can't reproduce this bug, feel free to reopen if you are still experiencing it.
