### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by mhnamaki** [Kaggle/kaggle-api#200]
I'm downloading kernels scripts and I've got "too many requests".
Please let me know what should be the wait time between every two requests to avoid getting such an error.

Thanks.

**Comment by tiyunchen** [comment]
+1, and how many requests will got  "too many requests".

**Comment by pawelgodula** [comment]
+1 on lyft dataset

**Comment by cmpute** [comment]
+1 on lyft dataset

**Comment by vakkov** [comment]
+1 on lyft's 3d object detection

**Comment by scofield1991** [comment]
did anyone find a solution?

**Comment by rysteboe** [comment]
For people hitting errors on competition downloads, please update your client to the latest version `pip install --upgrade kaggle`

**Comment by HiteshAI** [comment]
same problem with vehicle dataset..?? Is there any solution. Updating doesn't help

**Comment by PotatoSpudowski** [comment]
This worked for me.

pip uninstall -y kaggle
pip install --upgrade pip
pip install kaggle==1.5.6

**Comment by alext234** [comment]
Seriously this has to be fixed please.
@PotatoSpudowski instructions works for me 

```
kaggle competitions download -c rsna-pneumonia-detection-challenge
```

**Comment by c2karansingh** [comment]
@PotatoSpudowski thanks this worked for me.

P.S used it in Google collab. Remove ! if using in command prompt
!pip uninstall -y kaggle
!pip install --upgrade pip
!pip install kaggle==1.5.6

**Comment by akuma527** [comment]
@PotatoSpudowski Thanks a ton! :)

**Comment by utukJ** [comment]
@PotatoSpudowski Thanks a lot!!

**Comment by jaimecorton** [comment]
Hello! I am trying to download a small subset of 5000 images with Kaggle API version 1.5.16 (most recent stable version up to date: December 2023) and I am still getting the same response code mentioned here (429 : Too Many Requests).

I am extracting the images from state-farm-distracted-driver-detection dataset ([https://www.kaggle.com/competitions/state-farm-distracted-driver-detection/data](https://www.kaggle.com/competitions/state-farm-distracted-driver-detection/data)).

The error message appears aproximately around the 100th image download.

I am using a simple function for that purpose:

```
for filename in selected_filenames:
    print(filename)
    kaggle.api.competition_download_file(file_name=f'imgs/train/{selected_dict[filename]}/{filename}',
                                         competition=COMPETITION,
                                         path=DATAPATH)
```

Is there any kind of waiting time needed between downloads, so that, the response message 429 doesn't appear? Thanks in advance.
