### ISSUE TITLE
"RuntimeError: can't start new thread"

### ISSUE THREAD

**Issue by muschellij2** [Kaggle/kaggle-api#220]
Was running into `RuntimeError: can't start new thread` error with `_start_new_thread(self._bootstrap, ())` on our computing cluster.  I believe this is a configuration issue on our end, but anyone who has run into it, I solved it by commenting out:

```python
self.pool = ThreadPool()
```
at 
https://github.com/Kaggle/kaggle-api/blob/0242647d8f964d2368b775933b4bfcf1ea52afed/kaggle/api_client.py#L85

Essentially:
```
cd ~/.local/lib/python3.7/site-packages/kaggle/
vi api_client.py
```

and then I can actually download or even run `kaggle --version`.

**Comment by Rochan-A** [comment]
Thanks for the suggestion! Worked like a charm for us :+1:

**Comment by joosepgit** [comment]
Also ran into this while trying to use the kaggle command on my university computing cluster. It worked, however this issue took me 3 hours to find thinking that I was doing something wrong. I even started manipulating the source code myself to see internal states at various stages, which is something a user should never have to do. I'm honestly baffled that this issue has been known since 2019 and was just closed under the assumption that anyone who runs into it should just comment out some line themselves...? 

It is especially frustrating when you are a user who is completely powerless in terms of the clusters configuration. Would anyone care to at least investigate why this might happen? What should I suggest the people that manage said cluster to change so that would not happen? How is a fix of "just comment this line out" in any way acceptable for an official api of one of the largest data science websites in the world?
