### ISSUE TITLE
Organizations Error

### ISSUE THREAD

**Issue by shivangdubey** [Kaggle/kaggle-api#325]
Seems like Kaggle has removed organizations model in the backend but not on the front end. Neither one can create a new organization nor can view any other organization.
This also brings difficulty in reaching the *Contributor* level. 
Solution:
Incorporating organizations page again or removing them completely.

**Comment by jplotts** [comment]
Hi @shivangdubey - you're right that Kaggle has deprecated organizations for the time being.  We're still working out plans for the future, but we appreciate your feedback.

This repository is specifically about the Kaggle API, so I'm going to close this issue since there's nothing to be done with the API as it does not support any organization commands.  As a heads up, feedback regarding Kaggle's website is generally best posted to our [Product Feedback](https://www.kaggle.com/product-feedback) forum, which is more closely monitored by the team.  Thanks!
