### ISSUE TITLE
datasets upload error string longer than 2147483647 bytes

### ISSUE THREAD

**Issue by RobWishart** [Kaggle/kaggle-api#35]
There seems to be a limit on file size for upload

Running ...

kaggle datasets version -m version -p fraudtraindata

gives ...

Upload successful: predictors.pkl (352B)
string longer than 2147483647 bytes
Upload unsuccessful: train_df.pkl
Dataset version creation error: See previous output

**Comment by rysteboe** [comment]
Yup, known issue.  Definitely want to fix this but after a bunch of investigation over the last week, it's not going to be trivial.  No ETA at this point unfortunately.

**Comment by rysteboe** [comment]
This should be fixed in 1.3.7.  Please be aware that right now, there isn't support for resuming uploads, so minor network hiccups could result in you needing to kill the upload and try again.  The only way to see if it's hanging is to check your computer's network use.  Needless to say, I don't think that that's a good thing, but I don't have a better solution in place yet.  It is definitely something I want to fix, though.  Please let me know if you have additional problems.
