### ISSUE TITLE
Upload dataset by API, but I can't find it in the kaggle datasets page

### ISSUE THREAD

**Issue by MrZhangKY** [Kaggle/kaggle-api#430]
I have upload a dataset by API, the commend is 
```
kaggle datasets init
kaggle datasets create
```

And it have been done like this
![image](https://user-images.githubusercontent.com/44896606/173845473-02c3101f-c7cc-4664-afdc-ab1f94411ab5.png)

But I can't find it form the  kaggle datasets page like this
![image](https://user-images.githubusercontent.com/44896606/173845725-6a44ccda-b03d-4866-94b6-b64ae0b31dcc.png)

Could you please tell me what should I do to use my dataset?

**Comment by Isaac-Flath** [comment]
I am also having this problem.  I get success for both creating new datasets and creating new versions, but it doesn't get reflected on kaggle.  Having this problem in both python api as well as CLI.

**Comment by rosbo** [comment]
Hi @MrZhangKY,

I see you have a dataset with the same filenames than you shared in your screenshot: https://www.kaggle.com/datasets/zhangkaiyu/2-us-pptpm-alberta-xxlarge-v2-cusmodel-cpctexts-v1

Did you have to upload it from the UI or did the dataset you uploaded with your CLI/python library was eventually available?

**Comment by rosbo** [comment]
Hi @Isaac-Flath,

Your dataset uploaded failed because it contains a filename with an invalid character:

```
Error during creation: File name contains invalid character (@): @PaxHeader
```

Can you try again after renaming the file and let me know how it goes?

In the coming months, we are looking at whether those constraint on invalid characters can be relaxed and we also want to add better error surfacing to the users.

Thank you

**Comment by Isaac-Flath** [comment]
@rosbo None of the filenames in my dataset have an @ character, or any other unusual character.  I'm not sure what to try or change since it's all standard characters.

I am having a hard time finding a list of invalid characters in the docs.  Does a list of the invalid characters exist that I can double check everything against?

**Comment by wcuk** [comment]
@Isaac-Flath We believe this is fixed; please give it another try (the @PaxHeader file was coming from the headers of the zip file and should have been excluded from the dataset)

**Comment by Isaac-Flath** [comment]
@wcuk  - It worked!  

Thank you both much for your help :)

**Comment by inkyusa** [comment]
Hi, I am having a similar issue but different error message 

```
Error during creation: An uploaded file or directory name contains an invalid character: File name contains invalid character (&): bad&name.ini
```

I have many *.whl files and none of them contains `&`.

**Comment by inkyusa** [comment]
Solved by replacing all files' names with just `package_name.whl` but there maybe exists a better solution.

**Comment by abodacs** [comment]
@inkyusa 

Did you solve your issue?
if yes, How?

Thanks

**Comment by inkyusa** [comment]
In my case, it caused due to a tar file, so that I excluded it while uploading. And created a whl from that tar source file to upload. Hope this helps.
