### ISSUE TITLE
not valid dataset sources when I pull / push

### ISSUE THREAD

**Issue by davidenitti** [Kaggle/kaggle-api#433]
when i try to run a new version of an existing notebook (perfectly working via web interface), it does not work because it doesn't properly load the datasets.
I run:
```
$kaggle kernels pull gan-gpu -p k_tmp -m
Source code and metadata downloaded to k_tmp
$ kaggle kernels push -p k_tmp
The following are not valid dataset sources and could not be added to the kernel: ['datasets/lamsimon/celebahq', 'datasets/jessicali9530/celeba-dataset']
Kernel version 179 successfully pushed.  Please check progress at ...
```
how can I solve the issue?

**Comment by svendaj** [comment]
I had similar issue with [chained notebooks (using output data of completed notebooks as input for your  #notebook)](https://www.kaggle.com/docs/notebooks#adding-data-sources). When I have pulled my existing notebook and let it create metadata file: 
```
(numer.ai) C:\Users\lsadmin>kaggle kernels pull svendaj/daily-submissions -m
Source code and metadata downloaded to C:\Users\lsadmin
```
resulting *kernel-metadata.json* file had in `"kernel_sources":` section all notebooks prefixed with `code\` like this:
```
"kernel_sources": [
    "code/svendaj/jos-xb-naive",
    "code/svendaj/jos-xb-smart",
    "code/svendaj/jos-xb-exa",
    "code/svendaj/jos-xb-no-over",
    "code/svendaj/jos-xb-lazy",
    "code/svendaj/jos-xb-ng",
    "code/svendaj/jos-lb-ng"
  ],
```
Pushing back pulled notebook caused similar issue to yours:
```
(numer.ai) C:\Users\lsadmin>kaggle kernels push
The following are not valid kernel sources and could not be added to the kernel: ['code/svendaj/jos-xb-naive', 'code/svendaj/jos-xb-smart', 'code/svendaj/jos-xb-exa', 'code/svendaj/jos-xb-no-over', 'code/svendaj/jos-xb-lazy', 'code/svendaj/jos-xb-ng', 'code/svendaj/jos-lb-ng']
Kernel version 28 successfully pushed.  Please check progress at https://www.kaggle.com/code/svendaj/daily-submissions
```
and notebook ended up with error, because indeed input notebooks were not added to run environment.

I have edited *kernel-metadata.json* file by removing `code\` prefix like this:
```
"kernel_sources": [
    "svendaj/jos-xb-naive",
    "svendaj/jos-xb-smart",
    "svendaj/jos-xb-exa",
    "svendaj/jos-xb-no-over",
    "svendaj/jos-xb-lazy",
    "svendaj/jos-xb-ng",
    "svendaj/jos-lb-ng"
  ],
```
pushed it again and this time it succeeded. 

Although I am not using datasets as input, I believe the source is the same bug in metadata creation and if you would remove the `datasets/` prefix in `"dataset_sources":` section of metadata file it would fix your problem. Of course, this is not the fix for this kaggle API issue which remains open.

**Comment by Philmod** [comment]
Internal bug: http://b/288415155

**Comment by Philmod** [comment]
https://github.com/Kaggle/kaggle-api/releases/tag/1.5.14
