### ISSUE TITLE
How to get the past competitions?

### ISSUE THREAD

**Issue by BiqiangWang** [Kaggle/kaggle-api#641]
hello，
I tried to get all the competitions using the "**kaggle competitions list**" command. 
However, I found that I could only get the competitions that are currently in progress. 
Is there any way I can get the competitions that have ended?

By the way, When I tried to use "--category all", some unexpected errors occurred. The full command and results are as follows:
```
kaggle competitions list --category all
400 - Bad Request - Unrecognized HostSegment enum value
```

**Comment by stevemessick** [comment]
Thanks for the report @BiqiangWang !

I think the active competitions are simply the first ones in the list. However, I couldn't get any competitions when I used the `--page` option, unless it was page 1. That is a bug.

I haven't tried all categories, but the ones I tried (other than `all`) worked. Since the default is `all` there is no loss of functionality, but it still should be fixed. Still, it only selected competitions from the first page, instead of listing 20 competitions in a category. That seems like another bug.

**Comment by BiqiangWang** [comment]
thanks for your reply! @stevemessick  
`--page` does have the above problem. However, when using the `--search` option, although the information of --page 2 and later can be obtained, there is still no past competition.
maybe this proves that the` kaggle competitions list` command cannot get past competitions ?

**Comment by BiqiangWang** [comment]
By the way, the version I am currently using is the latest 1.6.17

**Comment by stevemessick** [comment]
I've identified the problem. There's a mismatch between how the API interprets parameters and how the web-server does. I'm working on a resolution for that but it won't be released for a while, due to scheduling priorities. 

Currently, there is no way for the API to retrieve closed competitions.
